pipeline {
  environment {
    registry = "rawatshubham138/nextjs-cicd"
    registryCredential = 'dockerhub'
    dockerImage = ''
  } 
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'npm install'
        sh 'npm run build'
      }
    }
    stage('Test') {
      steps {
        sh 'npm test'
      }
    }
     stage('SonarQube Analysis') {
      steps {
        withSonarQubeEnv('SonarQube') {
          sh 'npm run sonar-scanner'
        }
      }
    }
    stage('Build Docker Image') {
      steps {
        script {
          dockerImage = docker.build registry + ":$BUILD_NUMBER"
          
        }
      }
    }
    stage('Push Docker Image') {
      steps {
        script {
          docker.withRegistry( '', 'registryCredential') {
            dockerImage.push()
          }
        }
      }
    }
    stage('Deploy') {
      steps {
        sh 'docker-compose down && docker-compose up -d'
      }
    }
  }
  post {
    success {
      slackSend channel: '#devops', color: 'good', message: "Build succeeded for ${env.JOB_NAME} ${env.BUILD_NUMBER}"
    }
    failure {
      slackSend channel: '#devops', color: 'danger', message: "Build failed for ${env.JOB_NAME} ${env.BUILD_NUMBER}"
    }
  }
}
